static const int MAX_SERVO_ANGLE = 270;
static const int MIN_SERVO_ANGLE = 0;
static const int NEUTRAL_SERVO_ANGLE = (MAX_SERVO_ANGLE + MIN_SERVO_ANGLE) / 2;
static const int SERVO_TICKS = 1023;
static const int RECEIVE_PIN = 8;   // Receiving wire in pin 8
static const int TRANSMIT_PIN = 9 ;  // Transmitting in pin 9
static const int NORTH_ID = 1;  // arbitrary ID
static const int EAST_ID = 2;  // arbitrary ID
static const int SOUTH_ID = 3;  // arbitrary ID
static const int WEST_ID = 4;  // arbitrary ID
static const int ACTION_RATE_MS = 100;
static const int TELEMETRY_RATE_MS = 100;
static const int NUM_ZEROING_TRIALS = 100;
static const int BAUD_RATE = 115200;
static const float ACCEL_COEF = 0.2;
static const float GYRO_COEF = 0.8;
static const int ACTIVATION_TIME = -1;
static const float PITCH_KP = 0.5;
static const float ROLL_KP = 0.2;
static const float YAW_KP = 0.5;